name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liSLLAF73zzJ1n6A"
GITHUB_OWNER = "Determina54"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nav.determina54.dpdns.org/api/auth"
NEXT_PUBLIC_API_URL="https://nav.determina54.dpdns.org/"

